### ISSUE TITLE
Queue doesn't live-update

### ISSUE THREAD

**Issue by TylerLubeck** [TylerLubeck/HalliganHelper-Bugs#2]
## Bug Report
- Description: In version 2, the queue would live update whenever there was a change to the request list for a course. In version 3, this stopped working.
- Full URL of the page that had the bug: www.halliganhelper.com/#course/X, where X is any course.
- Is there anything in the Javascript console? Paste it here:
  `WebSocket connection to 'wss://www.halliganhelper.com/ws/ta?subscribe-broadcast' failed: Error during WebSocket handshake: Unexpected response code: 504`
- Screenshots (if applicable): N/A

**Comment by tchebb** [comment]
This is fixed in the development version of the site and the fix will go live before the Fall semester.
